### ISSUE TITLE
System.Configuration.SettingsPropertyNotFoundException on first time installation

### ISSUE THREAD

**Issue by WetHat** [WetHat/OnenoteTaggingKit#89]
The OneNoteTaggingKit won't start up because a SettingsPropertyNotFoundException is thrown.

**Comment by WetHat** [comment]
[Fixed in latest release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v5.1.8437)

**Comment by buvar** [comment]
[taggingkit_8DB0F4C4D501631.log](https://github.com/WetHat/OnenoteTaggingKit/files/10742229/taggingkit_8DB0F4C4D501631.log)

The problem persists in the latest version, in my OneNote...

**Comment by jola16** [comment]
Still exists in the latest version that I've installed today. I.e.:

[SetupTaggingKitWiX.5.1.8437.msi](https://github.com/WetHat/OnenoteTaggingKit/releases/download/v5.1.8437/SetupTaggingKitWiX.5.1.8437.msi)

**Comment by jola16** [comment]
PS. It seems it work after doing a manual repair using the installer. I guess the actual fix was that the installer restarted some "COM Surrogate" (dllhost) process.

**Comment by buvar** [comment]
I freshly installed, started OneNote and the message appeared. Went to "Programs and functions", clicked "Repair" and now it starts normally. But, frankly, it's a strange installation process :-).  Thanks anyway for the tip!
